# -*- coding: utf-8 -*-
"""cnn_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DyIQgXfuZq1VIHjkNh1U60pqEOkW3wv

In this notebook, we will be creating a CNN (Convolutional Neural Network) based classifier for the classification of CIFAR-10 dataset.

**About the dataset**

CIFAR-10 dataset is a subset of CIFAR-100 having 80 million images of 100 different objects. CIFAR-10 takes 60,000 images for 10 classes from the original dataset in which 50,000 images are for training and 10,000 images are for testing.

The classes in the dataset are -
* airplane
* automobile
* bird
* cat
* deer
* dog
* frog
* horse
* ship
* truck
"""

!pip install tensorflow

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i])
    # The CIFAR labels happen to be arrays,
    # which is why you need the extra index
    plt.xlabel(class_names[train_labels[i][0]])
plt.show()

"""**Creating a CNN model**

We are going to create a CNN based classification model using *keras* module.
"""

model = models.Sequential()

model.add(layers.Conv2D(32,(3,3),activation='relu', input_shape=(32,32,3)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))

model.summary()

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

model.summary()

model.compile(optimizer='sgd',loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])
history = model.fit(train_images, train_labels, epochs=10,validation_data=(test_images, test_labels))

plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print(test_acc)

model.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])
history = model.fit(train_images, train_labels, epochs=10,validation_data=(test_images, test_labels))

plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print(test_acc)

# save model
model.save('final_model.keras') #previously saved as 'final_model.h5", a legacy

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import preprocessing, models

# load and prepare the image
def load_image(filename):
	# load the image
	img = preprocessing.image.load_img(filename, target_size=(32, 32))
	# convert to array
	img = preprocessing.image.img_to_array(img)
	# reshape into a single sample with 3 channels
	img = img.reshape(1, 32, 32, 3)
	# prepare pixel data
	img = img.astype('float32')
	img = img / 255.0
	return img

# load images and predict the classes with confidence
def run_examples(filenames):
	# load model once
	model = models.load_model('final_model.keras')

	plt.figure(figsize=(15, 5))

	for i, filename in enumerate(filenames):
		try:
			# load the image
			img = load_image(filename)
			# predict the class probabilities
			# Note: use softmax if the model was trained with from_logits=True
			predictions = model.predict(img)
			# Convert logits to probabilities if necessary
			prob = tf.nn.softmax(predictions[0]).numpy()

			result = np.argmax(prob)
			prediction = class_names[result]
			confidence = prob[result] * 100

			# display the image
			plt.subplot(1, len(filenames), i + 1)
			plt.imshow(preprocessing.image.load_img(filename))
			plt.title(f"{prediction}\n({confidence:.2f}%)")
			plt.axis('off')
			print(f"{filename}: {prediction} ({confidence:.2f}%)")
		except Exception as e:
			print(f"Could not process {filename}: {e}")

	plt.tight_layout()
	plt.show()

# List of images to predict
image_files = ['image1.jpg', 'image2.jpg', 'image3.jpg', 'image4.png']
run_examples(image_files)